### ISSUE TITLE
GitHub Pages for Documentation yield 404 Error

### ISSUE THREAD

**Issue by ssiccha** [Time0o/mpsym#6]
The page
https://time0o.github.io/TUD_computational_group_theory/
is not available.

**Comment by Time0o** [comment]
I forgot to update this when I changed the repository name, there was also a problem with the Travis build. Should be available now [here](https://time0o.github.io/mpsym). Note that the documentation is somewhat incomplete and mostly concerns internals. I will add installation and usage instructions in the near future.
